### ISSUE TITLE
Methods Section 

### ISSUE THREAD

**Issue by steven-albanese** [choderalab/kinase-ecoli-expression-panel#6]
@Lucelenie : I left a hard copy of the manuscript with a bunch of edits to the protein expression methods section on your desk! I made what I thought were the most pressing edits, but I think that section could be rearranged a bit after we get it up on bioRxiv

**Comment by jchodera** [comment]
Did these edits make it in, @Lucelenie?  If so, please close.

**Comment by Lucelenie** [comment]
@jchodera : Yes, I added them!
