### ISSUE TITLE
IMPORTANT: ug/mL vs ng/uL

### ISSUE THREAD

**Issue by jchodera** [choderalab/kinase-ecoli-expression-panel#9]
It looks like the current manuscript has some major confusion over the numbers we report for expression yields.

The Caliper GX II yields are reported by the MacroLab in "ng/ul", which actually represents the number of nanograms of protein per microliter of sample loaded onto the Caliper.  The sample comes from the eluted protein that came off the beads in the Nickel Buffer A incubation and wash (120 uL).  Presumably, a few uL (how many) of this were loaded into the Caliper for quantification, and the final reported number is the concentration of this 120 uL eluate.  The "ng/ul" number is not informative without reporting how many total uL of eluate we got from the culture volume, and how much that culture volume was.

The original culture volume was 900 uL, so Danny and I had been converting the ng/ul number to "ug/mL of bacterial culture" by multiplying by (eluate volume) / (culture volume).  This is why the [online table](http://choderalab.github.io/kinome-data/kinase_constructs-addgene_hip_sgc.html) lists number 12 M3K5_HUMAN_D0 as 105 ng/ul but 12.6 mg/L expected scale-up: we appear to have calculated this as (105 ng/ul eulate) \* (120 uL eluate) / (1000 uL culture) = 12.6 mg/mL culture (where you see we have erroneously assumed we had 1 mL culture instead of 0.9 mL culture).  There seem to be some other issues with rounding in the online table from Danny as well----for ABL1_HUMAN_D0, the mg/L number 2.26 is truncated to 2.2 instead of being rounded to 2.3.

Can you guys fix the manuscript with this in mind?  I'll check in my edits in just a few minutes, and then you can have a go at it.  At minimum, we need to make sure we're talking about the right thing when we quote the yield or how many kinases expressed with a certain yield.  Even better would be to draw a threshold of, say, 1 or 2 mg/L expected scale-up, since it isn't very reasonable to use this method for the kinases expressing way down at 0.27 mg/L (2 ng/ul eluate).  That will drop the number of kinases we report as expressing, but will make it less embarrassing than suggesting people should use the kinase constructs that barely express.

Tagging @Lucelenie, @sonyahanson, @steven-albanese

**Comment by sonyahanson** [comment]
Lucelenie had asked me a few days ago how the mg/L expected scale-up conversion was made, and I couldn't answer, so thanks for clarifying this!

So, just to summarize: 
- You would like us to fix the calculation to use 0.9 mL of culture instead of 1 ml and change to using this mg/L value in the table and figure legend for the kinase tree.
- You would like us to change the expression cut-off we use to 2 mg/L, according to this new calculation, and change any current occurrence of the 68 expressable kinases to whatever this new number ends up being.

**Comment by jchodera** [comment]
Yes on both counts!

**Comment by jchodera** [comment]
You can punt on updating the figures if pressed for time.  The most important thing is the number of expressing kinases and making sure we don't use the wrong scale-up.

**Comment by danielparton** [comment]
Just in case this wasn't clear, the data used to make the online table can
be found in this folder:
https://github.com/choderalab/kinase-ecoli-expression-panel/tree/master/expression-constructs/addgene_hip_sgc/results-post_expression_testing

The Excel spreadsheet is what I believe John originally sent me, and this
includes the formula used to calculate the "expected scale-up" values.

**Comment by sonyahanson** [comment]
Working on this now.

Just to clarify, this calculation:

>  calculated this as (105 ng/ul eulate) \* (120 uL eluate) / (1000 uL culture) = 12.6 mg/mL culture (where you see we have erroneously assumed we had 1 mL culture instead of 0.9 mL culture).

Is supposed to be mg/L and not mg/ml, right?

**Comment by jchodera** [comment]
Yes, mg/L!

**Comment by jchodera** [comment]
Nick Levinson comments:

> experimentalists may be skeptical that the small-scale expression trials will scale up in large shaker flasks. So I would add a few sentences discussing the agreement between your screening results and the large scale expression yields obtained by others for a few examples.

I think we should revise the manuscript to be clear about summarizing our data in ug/mL culture, and then discuss (as Nick suggests) the correlation between ug/mL culture and mg/L culture in actual scale-up experiments:

> For instance, I see that you're results predict that abl expresses at relatively low levels, src better, and Csk very well. This has been verified by myself and markus, and probably others. On the other hand there are some strong deviations from the predictions; in our hands Aurora A and Cdk2 are among the best expressers I've seen at up to 40-60 mg/L. So I might emphasize that the results should be considered to be proof of the potential for successful bacterial expression, and give some indication of level, but that construct optimization can likely be used to significantly boost the expression levels of the kinases at the bottom of your table.

**Comment by jchodera** [comment]
We should also update the online table once we get all these conversions sorted out.

**Comment by danielparton** [comment]
FYI, the code for the online table is stored here:
https://github.com/choderalab/kinome-data/tree/gh-pages

It's just a static HTML page, generated by running this Python script:
https://github.com/choderalab/kinome-data/blob/gh-pages/pythonscripts/gen-html-plasmids-addgene_hip_sgc.py
The input data filepaths are hard-coded, so you'll probably need to change
those. Relevant lines: 18 and 21

If there are rounding errors in the table, that's probably some
misconfiguration of the DataTables js package.
The DataTables configuration is in this template file:
https://github.com/choderalab/kinome-data/blob/gh-pages/app/templates/expression-construct-table.html

Any problems, let me know.

**Comment by danielparton** [comment]
Just added a README.md

https://github.com/choderalab/kinome-data/tree/gh-pages

**Comment by jchodera** [comment]
I'm looking into this again.
- The spreadsheet `corrected_470_Report_Expression_Test_Results.xls` in `expression-constructs/addgene_hip_sgc/results-post_expression_testing` does appear to be correctly computing the expected scaleup in mg/L culture.
- The table in the paper seems to be fine.  I'm making some minor tweaks.

I'll update the kinome data page shortly.

**Comment by jchodera** [comment]
I've updated the online data table, though there are still plenty of other things to fix.  We'll have to find a more sustainable way to keep all this data together and organized---things are currently scattered in random places across multiple repos right now, and it currently takes a huge amount of work to even figure out what we have and how to wrangle it whenever something minor (like the conversion factor) needs to be changed.
